// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIADAL.Data;

#nullable disable

namespace SIADAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511040756_AddTemarioTable")]
    partial class AddTemarioTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SIADAL.Models.AcademicPeriod", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("end_date")
                        .HasColumnType("date");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly>("start_date")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.ToTable("academic_periods", (string)null);
                });

            modelBuilder.Entity("SIADAL.Models.Assignment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("class_id")
                        .HasColumnType("int");

                    b.Property<string>("details")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("duedate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("id");

                    b.HasIndex("class_id");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("SIADAL.Models.Class", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("period_id")
                        .HasColumnType("int");

                    b.Property<int>("program_id")
                        .HasColumnType("int");

                    b.Property<string>("schedule_json")
                        .HasColumnType("json");

                    b.Property<int>("teacher_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("period_id");

                    b.HasIndex("program_id");

                    b.HasIndex("teacher_id");

                    b.ToTable("classes", (string)null);
                });

            modelBuilder.Entity("SIADAL.Models.EducationalLevel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("educational_levels", (string)null);
                });

            modelBuilder.Entity("SIADAL.Models.Enrollment", b =>
                {
                    b.Property<int>("student_id")
                        .HasColumnType("int");

                    b.Property<int>("class_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("enrolled_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("student_id", "class_id");

                    b.HasIndex("class_id");

                    b.ToTable("enrollments", (string)null);
                });

            modelBuilder.Entity("SIADAL.Models.Program", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("level_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("id");

                    b.HasIndex("level_id");

                    b.ToTable("programs", (string)null);
                });

            modelBuilder.Entity("SIADAL.Models.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SIADAL.Models.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("birth_date")
                        .HasColumnType("date");

                    b.Property<string>("enrollment_number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("program_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("enrollment_number")
                        .IsUnique();

                    b.HasIndex("program_id");

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("SIADAL.Models.Submission", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("assignment_id")
                        .HasColumnType("int");

                    b.Property<string>("file_url")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("grade")
                        .HasColumnType("int");

                    b.Property<int>("student_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("submitted_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("id");

                    b.HasIndex("assignment_id");

                    b.HasIndex("student_id");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("SIADAL.Models.Teacher", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("employee_number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("employee_number")
                        .IsUnique();

                    b.HasIndex("user_id")
                        .IsUnique();

                    b.ToTable("teachers", (string)null);
                });

            modelBuilder.Entity("SIADAL.Models.Temario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("pdf_file_name")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("program_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("program_id");

                    b.ToTable("temarios", (string)null);
                });

            modelBuilder.Entity("SIADAL.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("password_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SIADAL.Models.role_user", b =>
                {
                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.HasKey("user_id", "role_id");

                    b.HasIndex("role_id");

                    b.ToTable("role_user", (string)null);
                });

            modelBuilder.Entity("SIADAL.Models.Assignment", b =>
                {
                    b.HasOne("SIADAL.Models.Class", "_class")
                        .WithMany("assignments")
                        .HasForeignKey("class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_class");
                });

            modelBuilder.Entity("SIADAL.Models.Class", b =>
                {
                    b.HasOne("SIADAL.Models.AcademicPeriod", "academic_periods")
                        .WithMany("classes")
                        .HasForeignKey("period_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIADAL.Models.Program", "program")
                        .WithMany("classes")
                        .HasForeignKey("program_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIADAL.Models.Teacher", "teacher")
                        .WithMany("classes")
                        .HasForeignKey("teacher_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("academic_periods");

                    b.Navigation("program");

                    b.Navigation("teacher");
                });

            modelBuilder.Entity("SIADAL.Models.Enrollment", b =>
                {
                    b.HasOne("SIADAL.Models.Class", "_class")
                        .WithMany("enrollments")
                        .HasForeignKey("class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIADAL.Models.Student", "student")
                        .WithMany("enrollments")
                        .HasForeignKey("student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_class");

                    b.Navigation("student");
                });

            modelBuilder.Entity("SIADAL.Models.Program", b =>
                {
                    b.HasOne("SIADAL.Models.EducationalLevel", "educational_levels")
                        .WithMany("programs")
                        .HasForeignKey("level_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("educational_levels");
                });

            modelBuilder.Entity("SIADAL.Models.Student", b =>
                {
                    b.HasOne("SIADAL.Models.Program", "program")
                        .WithMany("students")
                        .HasForeignKey("program_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIADAL.Models.User", "user")
                        .WithOne("student")
                        .HasForeignKey("SIADAL.Models.Student", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("program");

                    b.Navigation("user");
                });

            modelBuilder.Entity("SIADAL.Models.Submission", b =>
                {
                    b.HasOne("SIADAL.Models.Assignment", "assignment")
                        .WithMany("submissions")
                        .HasForeignKey("assignment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIADAL.Models.Student", "student")
                        .WithMany("submissions")
                        .HasForeignKey("student_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("assignment");

                    b.Navigation("student");
                });

            modelBuilder.Entity("SIADAL.Models.Teacher", b =>
                {
                    b.HasOne("SIADAL.Models.User", "user")
                        .WithOne("teacher")
                        .HasForeignKey("SIADAL.Models.Teacher", "user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("SIADAL.Models.Temario", b =>
                {
                    b.HasOne("SIADAL.Models.Program", "program")
                        .WithMany("temarios")
                        .HasForeignKey("program_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("program");
                });

            modelBuilder.Entity("SIADAL.Models.role_user", b =>
                {
                    b.HasOne("SIADAL.Models.Role", "role")
                        .WithMany("role_users")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIADAL.Models.User", "user")
                        .WithMany("role_users")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");

                    b.Navigation("user");
                });

            modelBuilder.Entity("SIADAL.Models.AcademicPeriod", b =>
                {
                    b.Navigation("classes");
                });

            modelBuilder.Entity("SIADAL.Models.Assignment", b =>
                {
                    b.Navigation("submissions");
                });

            modelBuilder.Entity("SIADAL.Models.Class", b =>
                {
                    b.Navigation("assignments");

                    b.Navigation("enrollments");
                });

            modelBuilder.Entity("SIADAL.Models.EducationalLevel", b =>
                {
                    b.Navigation("programs");
                });

            modelBuilder.Entity("SIADAL.Models.Program", b =>
                {
                    b.Navigation("classes");

                    b.Navigation("students");

                    b.Navigation("temarios");
                });

            modelBuilder.Entity("SIADAL.Models.Role", b =>
                {
                    b.Navigation("role_users");
                });

            modelBuilder.Entity("SIADAL.Models.Student", b =>
                {
                    b.Navigation("enrollments");

                    b.Navigation("submissions");
                });

            modelBuilder.Entity("SIADAL.Models.Teacher", b =>
                {
                    b.Navigation("classes");
                });

            modelBuilder.Entity("SIADAL.Models.User", b =>
                {
                    b.Navigation("role_users");

                    b.Navigation("student");

                    b.Navigation("teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
